"""create AgentForge v1 persistence model

Revision ID: 1b98633917fc
Revises:
Create Date: 2026-07-21 09:29:48.028576
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1b98633917fc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_type", sa.String(length=32), nullable=False),
        sa.Column("trigger_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("target_alias", sa.String(length=64), nullable=False),
        sa.Column("target_version", sa.String(length=255), nullable=False),
        sa.Column("category_scope", sa.String(length=100), nullable=True),
        sa.Column("subcategory_scope", sa.String(length=100), nullable=True),
        sa.Column("max_cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("max_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("max_mutations", sa.Integer(), nullable=False),
        sa.Column("no_signal_limit", sa.Integer(), nullable=False),
        sa.Column("actual_cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("actual_attempts", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "sanitized_error",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("cancellation_requested", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_campaigns_idempotency_key")),
    )
    op.create_index(
        "ix_campaigns_category_subcategory",
        "campaigns",
        ["category_scope", "subcategory_scope"],
        unique=False,
    )
    op.create_index(op.f("ix_campaigns_status"), "campaigns", ["status"], unique=False)
    op.create_index(
        "ix_campaigns_status_created_at", "campaigns", ["status", "created_at"], unique=False
    )
    op.create_index("ix_campaigns_target_version", "campaigns", ["target_version"], unique=False)
    op.create_table(
        "target_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=32), nullable=False),
        sa.Column("version_label", sa.String(length=255), nullable=False),
        sa.Column("git_sha", sa.String(length=64), nullable=True),
        sa.Column("deployment_id", sa.String(length=255), nullable=True),
        sa.Column("base_url_alias", sa.String(length=255), nullable=False),
        sa.Column("target_profile_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_target_versions")),
        sa.UniqueConstraint("version_label", name=op.f("uq_target_versions_version_label")),
    )
    op.create_table(
        "attack_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("attack_family_id", sa.String(length=255), nullable=False),
        sa.Column("parent_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("mutation_generation", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("subcategory", sa.String(length=100), nullable=False),
        sa.Column(
            "owasp_mappings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column(
            "proposed_sequence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "executed_sequence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("taxonomy_version", sa.String(length=64), nullable=False),
        sa.Column("profile_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "evidence_summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("evidence_hash", sa.String(length=64), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("langfuse_trace_id", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_attack_attempts_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_attempt_id"],
            ["attack_attempts.id"],
            name=op.f("fk_attack_attempts_parent_attempt_id_attack_attempts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attack_attempts")),
    )
    op.create_index(
        op.f("ix_attack_attempts_campaign_id"), "attack_attempts", ["campaign_id"], unique=False
    )
    op.create_index(
        "ix_attack_attempts_category_subcategory",
        "attack_attempts",
        ["category", "subcategory"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attack_attempts_evidence_hash"), "attack_attempts", ["evidence_hash"], unique=False
    )
    op.create_index(
        "ix_attack_attempts_trace_id", "attack_attempts", ["langfuse_trace_id"], unique=False
    )
    op.create_table(
        "regression_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("target_version", sa.String(length=255), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("total_cases", sa.Integer(), nullable=False),
        sa.Column("passed_cases", sa.Integer(), nullable=False),
        sa.Column("reproduced_cases", sa.Integer(), nullable=False),
        sa.Column("inconclusive_cases", sa.Integer(), nullable=False),
        sa.Column("error_cases", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_regression_runs_campaign_id_campaigns"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regression_runs")),
    )
    op.create_index(
        "ix_regression_runs_target_version", "regression_runs", ["target_version"], unique=False
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vulnerability_id", sa.String(length=64), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("source_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("subcategory", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("clinical_impact", sa.Text(), nullable=False),
        sa.Column("expected_behavior", sa.Text(), nullable=False),
        sa.Column("observed_behavior", sa.Text(), nullable=False),
        sa.Column("first_seen_target_version", sa.String(length=255), nullable=False),
        sa.Column("last_seen_target_version", sa.String(length=255), nullable=False),
        sa.Column("current_regression_case_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_attempt_id"],
            ["attack_attempts.id"],
            name=op.f("fk_findings_source_attempt_id_attack_attempts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
        sa.UniqueConstraint("fingerprint", name="uq_findings_fingerprint"),
        sa.UniqueConstraint("vulnerability_id", name=op.f("uq_findings_vulnerability_id")),
    )
    op.create_index(
        "ix_findings_category_subcategory", "findings", ["category", "subcategory"], unique=False
    )
    op.create_index("ix_findings_severity_status", "findings", ["severity", "status"], unique=False)
    op.create_table(
        "judge_verdicts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("exploitability", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "evidence_references",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "violated_invariants",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("next_recommendation", sa.Text(), nullable=False),
        sa.Column("rubric_hash", sa.String(length=64), nullable=False),
        sa.Column("rubric_version", sa.String(length=64), nullable=False),
        sa.Column("deterministic_override_applied", sa.Boolean(), nullable=False),
        sa.Column("deterministic_override_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attack_attempts.id"],
            name=op.f("fk_judge_verdicts_attempt_id_attack_attempts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_judge_verdicts")),
        sa.UniqueConstraint("attempt_id", name=op.f("uq_judge_verdicts_attempt_id")),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("finding_id", sa.Uuid(), nullable=True),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("langfuse_trace_id", sa.String(length=255), nullable=True),
        sa.Column(
            "typed_error",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attack_attempts.id"],
            name=op.f("fk_agent_runs_attempt_id_attack_attempts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_agent_runs_campaign_id_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_agent_runs_finding_id_findings"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(op.f("ix_agent_runs_attempt_id"), "agent_runs", ["attempt_id"], unique=False)
    op.create_index(op.f("ix_agent_runs_campaign_id"), "agent_runs", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_agent_runs_finding_id"), "agent_runs", ["finding_id"], unique=False)
    op.create_index(
        "ix_agent_runs_role_created", "agent_runs", ["role", "created_at"], unique=False
    )
    op.create_index("ix_agent_runs_trace_id", "agent_runs", ["langfuse_trace_id"], unique=False)
    op.create_table(
        "regression_cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("case_version", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "setup",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "ordered_sequence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "expected_security_invariants",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "deterministic_checks",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "judge_rubric_subset",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column(
            "owasp_mappings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "target_requirements",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_from_evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_regression_cases_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regression_cases")),
        sa.UniqueConstraint(
            "finding_id", "case_version", name=op.f("uq_regression_cases_finding_id")
        ),
    )
    op.create_index("ix_regression_cases_category", "regression_cases", ["category"], unique=False)
    op.create_index(
        op.f("ix_regression_cases_finding_id"), "regression_cases", ["finding_id"], unique=False
    )
    op.create_foreign_key(
        "fk_findings_current_regression_case_id_regression_cases",
        "findings",
        "regression_cases",
        ["current_regression_case_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "vulnerability_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("report_version", sa.Integer(), nullable=False),
        sa.Column(
            "structured_report",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("markdown_body", sa.Text(), nullable=False),
        sa.Column("markdown_path", sa.String(length=1024), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "validation_summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_vulnerability_reports_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vulnerability_reports")),
        sa.UniqueConstraint(
            "finding_id", "report_version", name=op.f("uq_vulnerability_reports_finding_id")
        ),
    )
    op.create_index(
        op.f("ix_vulnerability_reports_finding_id"),
        "vulnerability_reports",
        ["finding_id"],
        unique=False,
    )
    op.create_table(
        "regression_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("case_version", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column(
            "deterministic_results",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "judge_result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "evidence_references",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("trace_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["regression_cases.id"],
            name=op.f("fk_regression_results_case_id_regression_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["regression_runs.id"],
            name=op.f("fk_regression_results_run_id_regression_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regression_results")),
        sa.UniqueConstraint(
            "run_id", "case_id", "case_version", name=op.f("uq_regression_results_run_id")
        ),
    )
    op.create_index(
        "ix_regression_results_run_case", "regression_results", ["run_id", "case_id"], unique=False
    )
    op.create_index(
        op.f("ix_regression_results_trace_id"), "regression_results", ["trace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_regression_results_trace_id"), table_name="regression_results")
    op.drop_index("ix_regression_results_run_case", table_name="regression_results")
    op.drop_table("regression_results")
    op.drop_index(op.f("ix_vulnerability_reports_finding_id"), table_name="vulnerability_reports")
    op.drop_table("vulnerability_reports")
    op.drop_constraint(
        "fk_findings_current_regression_case_id_regression_cases",
        "findings",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_regression_cases_finding_id"), table_name="regression_cases")
    op.drop_index("ix_regression_cases_category", table_name="regression_cases")
    op.drop_table("regression_cases")
    op.drop_index("ix_agent_runs_trace_id", table_name="agent_runs")
    op.drop_index("ix_agent_runs_role_created", table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_finding_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_campaign_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_attempt_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_table("judge_verdicts")
    op.drop_index("ix_findings_severity_status", table_name="findings")
    op.drop_index("ix_findings_category_subcategory", table_name="findings")
    op.drop_table("findings")
    op.drop_index("ix_regression_runs_target_version", table_name="regression_runs")
    op.drop_table("regression_runs")
    op.drop_index("ix_attack_attempts_trace_id", table_name="attack_attempts")
    op.drop_index(op.f("ix_attack_attempts_evidence_hash"), table_name="attack_attempts")
    op.drop_index("ix_attack_attempts_category_subcategory", table_name="attack_attempts")
    op.drop_index(op.f("ix_attack_attempts_campaign_id"), table_name="attack_attempts")
    op.drop_table("attack_attempts")
    op.drop_table("target_versions")
    op.drop_index("ix_campaigns_target_version", table_name="campaigns")
    op.drop_index("ix_campaigns_status_created_at", table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_status"), table_name="campaigns")
    op.drop_index("ix_campaigns_category_subcategory", table_name="campaigns")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
